# Assignment 1: Wrangling data with pandas

For this assignment, note the following so that you receive credit for your work:  
- All of your final answers to the questions will be entered in this notebook - anywhere you see Blank 1 or Blank 2 etc indicates a space to fill in the answer to a question. **Answers embedded in code will not be graded** - ask if you do not know how to edit a markdown cell.
  
- All of your code used to answer the questions will be filled into this notebook. Make sure your code shows ALL of the necessary steps and is executable and clearly prints the outputs. You will upload the notebook to Blackboard as part of your assignment.

- Add in as many code cells as you need - it is often better to separate out statements into separate cells in case something goes wrong.
  
- Your code must relfect what was covered in class as well as your answers to questions. Both code and answers should be brief. **Overly verbose submissions and/or unnecesssarily complex submissions relying predominantly on structures not covered in class will not receive full credit and may receive no credit.**
  
- You are expected to have questions about the data and assignment - both clarifications and those related to your work. Be sure to post your clarification questions (don't reveal any answers) on Piazza so the entire class can benefit.

# Question 1 (3 Points)

If you used any online resources or collaborated with anyone, enter that information here. Also, remember that you are required to be able to explain and defend all of your work should you be asked.

Be as detailed as possible:
- If you visited any websites, include the URL and a description of what you were trying to figure out.
- If you used an AI tool, copy & paste the entire conversation, or if you had many prompts, save them into a document and write the document to .pdf and upload it - just indicate in the question block that you uploaded a file. Acceptable AI usage includes asking for help debugging code that you have written yourself, and asking for explanations and clarification of concepts or specific code structures to help you understand. **Plugging the questions into AI wholesale and copying the answers is not permitted** - plus, you need to use your brain so that you develop critical thinking skills because literally everyone on the planet can plug stuff into a chatbot.
- If you worked with a classmate, indicate who - you are welcome to complete assignments as a group of up to 4 people and turn in a single assignment (or the same assignment) - just put a comment in Blackboard with your names 
- If you only used your class notes (or nothing at all), indicate that. Do not leave this question blank.

Answer here: 
- **Teammates**: Mia Cummings
- **AI Usage**: planning on using ChatGPT to explain/teach me new code commands, interactive active recall, & debugging. Will probably use some some accidental gemini in google searches
- **Class Notes Usage**:
- **Websites Visited**:

# Question 2 (15 Points)
Start by importing the **species.csv** file into a pandas DataFrame. This file was sourced from the National Park Service and reports animals observed in National Parks. Each row corresponds to a species of animal observed in a specific park.

Fill in your code below and your answers to the following:
- The number of different reptile species identified in the parks as a whole: **[1343]** 
- The reptile species identified in the most parks: **[Pituophis catenifer]**
- How many parks this species was found in: **[24]**

In [1]:
# Fill in code here
import pandas as pd

df = pd.read_csv("species.csv")
df.head()
# df.shape

,Species ID,Park Name,Category,Order,Family,Scientific Name,Common Names,Record Status,Occurrence,Nativeness,Conservation Status
0,ACAD-1000,Acadia National Park,Mammal,Artiodactyla,Cervidae,Alces alces,Moose,Approved,Present,Native,NaN
1,ACAD-1001,Acadia National Park,Mammal,Artiodactyla,Cervidae,Odocoileus virginianus,"Northern White-Tailed Deer, Virginia Deer, Whi...",Approved,Present,Native,NaN
2,ACAD-1002,Acadia National Park,Mammal,Carnivora,Canidae,Canis latrans,"Coyote, Eastern Coyote",Approved,Present,Not Native,Species of Concern
3,ACAD-1003,Acadia National Park,Mammal,Carnivora,Canidae,Canis lupus,"Eastern Timber Wolf, Gray Wolf, Timber Wolf",Approved,Not Confirmed,Native,Endangered
4,ACAD-1004,Acadia National Park,Mammal,Carnivora,Canidae,Vulpes vulpes,"Black Fox, Cross Fox, Eastern Red Fox, Fox, Re...",Approved,Present,Unknown,NaN

In [2]:
#1
reptile_species = df['Category'].value_counts()
print(reptile_species)

# 2
df[df['Category'] == "Reptile"]['Scientific Name'].mode()

# 3
species_1 = df[df['Scientific Name'] == 'Pituophis catenifer']
print(species_1['Park Name'].nunique())

Category
Vascular Plant         65221
Bird                   14601
Insect                 14349
Fungi                   6203
Nonvascular Plant       4278
Fish                    3956
Mammal                  3867
Invertebrate            1566
Reptile                 1343
Algae                    976
Slug/Snail               787
Spider/Scorpion          776
Amphibian                743
Crab/Lobster/Shrimp      582
Name: count, dtype: int64
24

# Question 3 (7 Points)
How many parks have at least one endangered amphibian? **[4]**.

In [3]:
# Fill in code here
end = df['Conservation Status'] == 'Endangered'
amp = df['Category'] == 'Amphibian'
# print(df[end & amp]['Park Name'].count())
df[end & amp]['Park Name'].nunique()

4

# Question 4 (10 Points)
In order to reduce redundancy, someone suggests to leave Category in the table and remove the next 4 columns (from Family to Common Name). This is a terrible idea. Explain briefly why and what to do instead. You do not need to carry out the steps in code - please do not alter the current data frame. (There should be some questions on Piazza cropping up here.....)  

**[Category is the broadest naming convention, so an entry in Category doesn't uniquely determine Order, Order doesn't uniquely determine Family, and so forth. You should keep the most specific naming convention in the main table (imo its Scientific Name, Common Names are not atomic values so if you split it up that might not be the most specific uniquely identifying column), and move all the broader naming measures into a new table.]**.

# Question 5 (10 Points)
Something is wrong with the record status column. What is it and how did it probably happen? Is the problem actually only with the record status column? 

**[There are 6 missing values in the column, "Record Status", and upon further exploration, it seems that the Conservation Status also has missing values in the same columns. However Conservation status has 114530 columns with NaN, so there could be a potential functional dependcy where a NaN in Record Status could trigger an NaN in Conservation Status, or it could be just coincidence that both of these columns have NaN since there are so many Nan in conservation Status.]**

Include code below to support your answer.

In [4]:
# Fill in code here

# First we looked at the number of NaN's in Record Status. 
print('# of NaN in Record Status: ',df['Record Status'].isna().sum())
# Then we looked at the df of all the NaN's that exist in Record Status: df[df['Record Status'].isna() == True]
print('# of NaN in Conservation Status: ',df['Conservation Status'].isna().sum())
# Seeing how many NaN's are in the entire df by column
print(df.isna().sum())
# Displaying df of NaN's in Record Status just to compare
df[df['Record Status'].isna() == True]

# of NaN in Record Status:  6
# of NaN in Conservation Status:  114530
Species ID                  0
Park Name                   0
Category                    0
Order                    1472
Family                   1512
Scientific Name             0
Common Names            27147
Record Status               6
Occurrence              20142
Nativeness              25045
Conservation Status    114530
dtype: int64

,Species ID,Park Name,Category,Order,Family,Scientific Name,Common Names,Record Status,Occurrence,Nativeness,Conservation Status
96934,ROMO-3981,Rocky Mountain National Park,Fungi,Trichiales,Trichiaceae,Arcyria,pomiformis,NaN,In Review,Present,NaN
96943,ROMO-3990,Rocky Mountain National Park,Fungi,Trichiales,Trichiaceae,Trichia,alpina,NaN,In Review,Present,NaN
96944,ROMO-3991,Rocky Mountain National Park,Fungi,Trichiales,Trichiaceae,Trichia,botrytis,NaN,In Review,Present,NaN
96945,ROMO-3992,Rocky Mountain National Park,Fungi,Trichiales,Trichiaceae,Trichia,sordida,NaN,In Review,Present,NaN
96946,ROMO-3993,Rocky Mountain National Park,Fungi,Trichiales,Trichiaceae,Trichia,subfusca,NaN,In Review,Present,NaN
96947,ROMO-3994,Rocky Mountain National Park,Fungi,Trichiales,Trichiaceae,Trichia,varia,NaN,In Review,Present,NaN

# Question 6 (15 Points)
One thing we did not discuss in class was the use of `group_by` in pandas. `group_by` will partition the data in your data frame by the value of one or more variables - it divides it into chunks. It doesn't create a new data frame - you have to aggregate the values using a second method `agg` to tell it how to combine them. Looking up examples and further explanation of `group_by` and `agg` would be an acceptable and **great** use of AI, but also, you can definitely ask for examples and explanations on Piazza/in office hours.

We will group our data by Park Name and Category and then aggregate by count. There are a few accounting steps to make sure we have a proper index as well. We can do this with this line of code (it's one line, just long):  
  
`species[['Park Name', 'Category', 'Occurrence']].groupby(['Park Name','Category'], as_index = False).agg('count').reset_index(drop = True)`

Use this to transform the data. You will end up with a data frame with 3 columns.

- Brief explanation of what the occurrence column contains: **[Contains the number of animals within a category that are in a specific park.]** 
- Is this dataframe in 3NF? Why or why not? **[Yes. Passes 1NF because df is atomic, order is irrelevant, and primary key is (Park Name, Category). Passes 2NF because there are no partial dependencies as Occurrence value is determined by comination of Park Name & Category. Passes 3NF because there are no transitive depencies (nothing for Occurence to transitively depend on.)]**
- The park with the most bird species (Yo, this is a hint for Blank_1) **[Grand Canyon National Park]**
- The average number of bird species per park **[25.642 birds/park]**

In [5]:
bla = df[['Park Name', 'Category', 'Scientific Name', 'Occurrence']].groupby(['Park Name','Category', 'Scientific Name'], as_index = False).agg('count').reset_index(drop = True)
bla

bla[bla['Park Name']=='Acadia National Park']

,Park Name,Category,Scientific Name,Occurrence
0,Acadia National Park,Amphibian,Ambystoma laterale,1
1,Acadia National Park,Amphibian,Ambystoma maculatum,1
2,Acadia National Park,Amphibian,Bufo americanus,1
3,Acadia National Park,Amphibian,Desmognathus fuscus,1
4,Acadia National Park,Amphibian,Eurycea bislineata,1
...,...,...,...,...
1704,Acadia National Park,Vascular Plant,Xyris montana,1
1705,Acadia National Park,Vascular Plant,Zannichellia palustris,1
1706,Acadia National Park,Vascular Plant,Zizania aquatica,1
1707,Acadia National Park,Vascular Plant,Zizia aurea,1
1708,Acadia National Park,Vascular Plant,Zostera marina var. stenophylla,1

In [6]:
# Fill in code here:
new_df = df[['Park Name', 'Category', 'Occurrence']].groupby(['Park Name','Category'], as_index = False).agg('count').reset_index(drop = True)
bird = new_df[new_df['Category']== 'Bird']
bird[bird['Occurrence'] == bird['Occurrence'].max()]

# df
b = df[df['Category'] == 'Bird']
b_spcies = b['Scientific Name'].nunique()
parks = df['Park Name'].nunique()

avg = b_spcies / parks
print(avg)

25.642857142857142

# Question 7 (20 Points)
Create a table that shows the percentage of species of each category of organism in each park (out of the total number of species for just that park). Use the table from the question above and methods we discussed in class - it may be easiest to do this in two steps. Your resulting table will have only 1 row per park and the column names will be the categories (Reptile, Amphibian, etc.). 


- Number of parks with more than 25% of species that are fish **[Blank 1]**
- Category that is on average (just use the mean) the highest percentage across all parks **[Blank 2]**
- Is this table Tidy? Explain briefly why or why not. **[Blank_3]**

In [7]:
# Fill in code here:
# new_df is the df below
df[['Park Name', 'Category','Occurrence']].groupby(['Park Name','Category'], as_index = False).agg('count').reset_index(drop = True)

counts = new_df.pivot_table(
    index='Park Name',     # Column(s) to turn into Row Labels (Groups)
    columns='Category',   # Column(s) to turn into Column Headers
    values='Occurrence',    # Column(s) to aggregate
    aggfunc='sum',      # The math to apply (e.g., 'sum', 'count', 'mean')
).fillna(0)

perc = counts.div(counts.sum(axis=1), axis=0) * 100
perc.head()

Category,Algae,Amphibian,Bird,Crab/Lobster/Shrimp,Fish,Fungi,Insect,Invertebrate,Mammal,Nonvascular Plant,Reptile,Slug/Snail,Spider/Scorpion,Vascular Plant
Park Name,,,,,,,,,,,,,,
Acadia National Park,0.0,0.877706,21.299005,0.0,2.223523,0.000000,0.000000,0.000000,3.218256,0.000000,0.643651,0.0,0.000000,71.737858
Arches National Park,0.0,0.763359,19.561069,0.0,1.049618,0.000000,0.000000,0.000000,5.629771,0.000000,1.908397,0.0,0.000000,71.087786
Badlands National Park,0.0,0.797166,21.169176,0.0,2.125775,4.340124,9.388840,0.088574,5.580159,0.000000,1.151461,0.0,0.088574,55.270151
Big Bend National Park,0.0,0.583221,18.528488,0.0,2.288022,0.000000,0.000000,0.000000,3.947959,2.108569,2.781516,0.0,0.000000,69.762225
Biscayne National Park,0.0,0.495970,14.259144,0.0,43.955363,0.000000,0.681959,2.107874,1.673900,0.000000,2.479851,0.0,0.000000,34.345939

In [8]:
# x = count(species==fish) / total species
# cond = x>25
# end goal: number of parks
perc['Park Name']['Scientific Name']>0.25.count()

KeyError: 'Park Name'

### Bonus (+1 pt)  

What is a cool (classroom appropriate) thing you heard in a podcast or read on the news lately? Or what is a (classroom appropriate) book/movie/TV show you recommend?

Frieren: Beyond Journey's End