In [2]:
import pandas as pd
import sqlite3

In [3]:
#Create a connection to the db - call it cafe_new.db
conn = sqlite3.connect('cafe_new.db')

In [4]:
#Create a cursor
curs = conn.cursor()

In [5]:
#Enforce foreign keys
curs.execute("PRAGMA foreign_keys=ON;")

## Create the Drink_Type Table

In [ ]:
sql = '''
CREATE TABLE Drink_Type(
   drink_name TEXT PRIMARY KEY,
   category TEXT NOT NULL  
);
'''
# constraint 1 = primary key
#constraint 2 = not null 
#we can do this CREATE TABLE IF NOT EXISTS

In [7]:
curs.execute(sql) #different from what we did before - cursor directly executes the statements

In [8]:
curs.fetchall() #fetchall will get the results and print them

[]

Using the cursor directly to get a list of tables ("PRAGMA table_list")

In [9]:
curs.execute("PRAGMA table_list")
curs.fetchall()

[('main', 'Drink_Type', 'table', 2, 0, 0),
 ('main', 'sqlite_schema', 'table', 5, 0, 0),
 ('temp', 'sqlite_temp_schema', 'table', 5, 0, 0)]

Versus pandas (when we know we are getting a table of output)

In [15]:
pd.read_sql("PRAGMA table_list", conn)

  schema                name   type  ncol  wr  strict
0   main          Drink_Type  table     2   0       0
1   main       sqlite_schema  table     5   0       0
2   temp  sqlite_temp_schema  table     5   0       0

In [17]:
pd.read_sql("PRAGMA table_info(drink_type)", conn)
# pk = primary key
# dflt_value = default value

   cid        name  type  notnull dflt_value  pk
0    0  drink_name  TEXT        0       None   1
1    1    category  TEXT        1       None   0

In [11]:
#let's try to add a row or two
#more on syntax later
sql = """
INSERT INTO Drink_Type
VALUES('Mocha',NULL)
"""

In [12]:
curs.execute(sql)

IntegrityError: NOT NULL constraint failed: Drink_Type.category

have to drop table then alter it, sql lite doesn't let you change the table once initiated??

In [ ]:
#let's try to add a row or two
#more on syntax later
sql = """
INSERT INTO Drink_Type
VALUES('Mocha','Chocolate')
"""

In [ ]:
sql = """
INSERT INTO Drink_Type
VALUES();
"""
#give me a row we could add

In [ ]:
pd.read_sql("PRAGMA table_info(Drink_Type)", conn)

What if I want to change the constraints after the fact? SQLite doesn't allow this with ALTER TABLE...hmmm...can we re-create it?

In [ ]:
sql = '''
CREATE TABLE Drink_Type(
   drink_name TEXT NOT NULL PRIMARY KEY,
   category TEXT NOT NULL
)
'''

In [ ]:
curs.execute(sql)

In [ ]:
#what do we have to do first?

In [ ]:
curs.execute(sql)

In [ ]:
pd.read_sql("PRAGMA table_list", conn)

In [ ]:
pd.read_sql("PRAGMA table_info(Drink_Type)", conn)

## Create Sells Table

In [ ]:
sql ="""
CREATE TABLE Sells(
    cafe_name TEXT NOT NULL,
    drink_name TEXT NOT NULL,
    price_usd REAL NOT NULL CHECK(price_usd > 0),
    PRIMARY KEY(cafe_name, drink_name),
    FOREIGN KEY(drink_name) REFERENCES Drink_Type(drink_name)
);
"""

if you run the above code and it works, u know for certain Drink_Type table exists.

In [ ]:
curs.execute(sql)

In [ ]:
sql = "SELECT * FROM sqlite_master;"
result = pd.read_sql(sql, conn)
result
#curs.execute(sql)
#curs.fetchall()

In [ ]:
pd.read_sql("PRAGMA table_info(Sells);", conn)

In [ ]:
pd.read_sql("PRAGMA foreign_key_list(Sells);", conn)
#curs.execute("PRAGMA foreign_key_list(Sells)")
#curs.fetchall()

In [ ]:
sql = """
INSERT INTO Sells
VALUES('Starbucks','Cafe Latte','5.25');
"""

In [ ]:
curs.execute(sql)

In [ ]:
#How do we fix this?
sql = """

"""

In [ ]:
curs.execute(sql)

In [ ]:
sql = """
INSERT INTO Sells
VALUES('Starbucks','Cafe Latte','5.25');
"""

In [ ]:
curs.execute(sql)

In [ ]:
sql = """
SELECT * FROM Sells"""
pd.read_sql(sql, conn)

In [ ]:
sql = """
INSERT INTO Sells
VALUES('Starbucks','Cafe Latte','5.25');
"""

In [ ]:
curs.execute(sql)

In [ ]:
sql = """
INSERT INTO Sells
VALUES('Starbucks','Mocha','-5.25');
"""

In [ ]:
curs.execute(sql)

In [ ]:
conn.commit()

like git, need to commit for the database to update permanently, then close out of database

In [ ]:
conn.close()