Note: This review is not comprehensive. Make sure you take notes in class on other things to review for the midterm.

In [1]:
import pandas as pd
import sqlite3

WHERE row value condition < == > or smth  -- relational algebra selection
SELECT column1, column2, -- relational algebra projection
union adds rows
join adds cols
union removes duplicates
union all does not

For this review, we will use a database with two relations in it:  

Category(Incident_Type, Category) with Incident_Type as the Primary Key  
  
Incidents_Money(Incident_ID, Incident_Type, Estimated_Contents_Loss,Civilian_Injuries) with Incident_ID as the Primary Key and Incident_Type as a Foreign Key  
  
This data was sourced from publicly available information from the Virginia Beach Fire Department. Categories were made up for the purpose of this exercise and are not part of VBFD data.  

Incident_ID cannot be null in the Incidents_Money table and Incident_Type cannot be null in the Category table.

Given that both primary keys are valid, why wouldn't we just put all of these columns into the same table? What normalization properties would that violate?

If Incident_ID is a valid primary key for the Incidents_Money table, what attributes must be in its closure?

### Now we will start working with the database

In [2]:
conn = sqlite3.connect("fire.db")

In [3]:
curs = conn.cursor()

In [4]:
curs.execute("PRAGMA foreign_keys=ON;")

In [5]:
sql = """
PRAGMA table_list;
"""

In [6]:
pd.read_sql(sql, conn)

  schema                name   type  ncol  wr  strict
0   main     incidents_money  table     4   0       0
1   main            Category  table     2   0       0
2   main       sqlite_schema  table     5   0       0
3   temp  sqlite_temp_schema  table     5   0       0

In [7]:
sql = """
SELECT *
FROM incidents_money
LIMIT 5;
"""

In [8]:
pd.read_sql(sql, conn)

,Incident_ID,Incident_Type,Estimated_Contents_Loss,Civilian_Injuries
0,2016050936,"EMS call, excluding vehicle accident with injury",0.0,NaN
1,2013022494,"EMS call, excluding vehicle accident with injury",0.0,NaN
2,2016048081,"Alarm system activation, no fire - unintentional",0.0,NaN
3,2021043224,Passenger vehicle fire,0.0,1.0
4,2018003513,"Excessive heat, scorch burns with no ignition",0.0,NaN

In [9]:
sql = """
SELECT *
FROM Category
LIMIT 5;
"""

In [10]:
pd.read_sql(sql, conn)

                                      Incident_Type Category
0  EMS call, excluding vehicle accident with injury      EMS
1  Alarm system activation, no fire - unintentional    Alarm
2                            Passenger vehicle fire     Fire
3     Excessive heat, scorch burns with no ignition     Fire
4                                    Public service    Other

First, we are going to try to insert another row into the Incidents_Money table:

In [11]:
sql = """
INSERT INTO Incidents_Money
VALUES('201652372','Motorcycle Accident',0,NULL );
"""

In [12]:
curs.execute(sql)

OperationalError: database is locked

Why does this fail?

We then try to add this row (tuple) and it fails for a different reason...why?

In [ ]:
sql = """
INSERT INTO Incidents_Money
VALUES(NULL,'Building Fire',0,NULL );
"""

In [ ]:
curs.execute(sql)

OperationalError: no such table: Incidents_Money

Next we would like to identify incidents where the contents loss is greater than $100 - write the query to do this.

In [ ]:
sql = """

"""

In [ ]:
pd.read_sql(sql, conn)

TypeError: 'NoneType' object is not iterable

What is the relational algebra for this?

We would like to find Incidents where the Estimated Contents Loss is greater than the average amount. Write the query to do this.

In [ ]:
sql = """

"""

In [ ]:
pd.read_sql(sql, conn)

We would like to find Incident_ID and Incident_Type for individual incidents of type Fire. Write the query to do this.

In [ ]:
sql = """

"""

In [ ]:
pd.read_sql(sql, conn)

What is a second way you could write this query?

In [ ]:
sql = """

"""

In [ ]:
pd.read_sql(sql, conn)

We are going to use a Union to get Incident_ID, Incident_Type and Category for all incidents in the category Fire and all incidents with >$100 loss. Then, we will do this a better way :)

In [ ]:
#first do this with a union of two subqueries
sql = """SELECT Incident_ID, Incident_Type, Category
FROM Incidents_Money
JOIN Category
USING(Incident_Type)
WHERE Category = 'Fire'
UNION
SELECT Incident_ID, Incident_Type, Category
FROM Incidents_Money
JOIN Category
USING(Incident_Type)
WHERE Estimated_Contents_Loss > 100"""

In [ ]:
pd.read_sql(sql, conn)

In [ ]:
#first do this with a union of two subqueries
sql = """SELECT Incident_ID, Incident_Type, Category
FROM Incidents_Money
JOIN Category
USING(Incident_Type)
WHERE Category = 'Fire'
UNION ALL
SELECT Incident_ID, Incident_Type, Category
FROM Incidents_Money
JOIN Category
USING(Incident_Type)
WHERE Estimated_Contents_Loss > 100"""

In [ ]:
pd.read_sql(sql, conn)

What is different between these two queries in terms of the output? Why?

What is a much simpler way to do this?

In [ ]:
sql = """

"""

In [ ]:
pd.read_sql(sql, conn)

In [ ]:
conn.close()